# Python Basics

In this section, we're going to go over some basics of Python. This is a slight step up from being COMPLETELY new to Python - I will assume you have a tiny bit of background knowledge. If you're completely new, I recommend going to a website like Khan Academy or Code Acaemy to get a grasp on your fundamentals.

Python codes are traditionally executed from ".py" files: you write some code, put it in a .py file, run the .py file, and the file will do what you coded up. However, that's not the easiest way to use Python. Folks typically use Python notebooks like these (.ipynb files): these are easier to interact with and edit, but take a little more setting up.

If you're reading this, we've presumably set up Python on your computers, and have downloaded some sort of interface to use Python notebooks with. Most people use Jupyter (through Anaconda), I'm using a Microsoft software called VSCode. Use whatever you feel comfortable with, although I recommed Jupyter Notebooks since those are so widely used (and hopefully easier to troubleshoot). 

Instead of executing .py files, we interact with blocks of code in Python notebooks. Let's execute your first line of code. You may get a message asking what Python environment you want to use - click the Python environment that you installed numpy, matplotlib, and astropy to. You can install these modules by typing "pip install [module name]" into a terminal, but I will have a separate tutorial for installing modules.

Code blocks can be thought of as mini .py files - each code block can contain your code and can be executed. Code blocks can also remember the output from code blocks that were executed before it, but be VERY CAREFUL OF THE ORDER THEY ARE EXECUTED IN!

### Click on the block below, and press SHIFT + ENTER to execute it.

In [1]:
print("Howdy, world!")

Howdy, world!


## DATA TYPES & OPERATIONS

Let's explore the different data types in Python. There are [many](https://docs.python.org/3/library/stdtypes.html) data types, but we'll focus on the ones that are most commonly used in astronomy:

- strings  (text),
- ints (integers),
- and floats (decimals).

Go through and execute the following blocks, and make sure you understand the differences between data types.

### ints (integers)

In [1]:
x = 5
y = 123
z = 69

print(x, y, z)

5 123 69


### floats (floating point values)

In [2]:
i = 23.7
j = -4.20
k = 3e7

print(i, j, k)

23.7 -4.2 30000000.0


### strings (text, basically)

In [4]:
a = 'frank is cool'
b = '27'
c = '42.86'

print(a, b, c)

frank is cool 27 42.86


One can convert in between data types using int(), str(), and float(). Try converting the variables b and c from the code block above into an integer and float respectively. You'll notice that you can now do arithmetic with the new variables d and e, when you couldn't do it before with variables b and c:

In [8]:
d = int(b)
e = float(c)

print('variable d + variable e = %s' %(d+e))
print('variable b + variable c = %s' %(b+c))

variable d + variable e = 69.86
variable b + variable c = 2742.86


This also shows how adding string C to string B just tacks the characters in string C to the end of the characters in string B. 

Also, the "%s" operator formats strings: "%s" is replaced by whatever is within the %() brackets when printed. Explicitly, the string "Howdy, %s" %(world!) would be printed out as "Howdy, world!".

That being said, there are limitations to what data types you can convert. Variable a contains no numbers: what happens when we try to convert that to a float? Execute the block below.

In [9]:
float(a)

ValueError: could not convert string to float: 'frank is cool'

One can check what data type a variable is using type():

In [22]:
print(type(a), type(z), type(i))

<class 'str'> <class 'int'> <class 'float'>


Moving on: we've briefly touched upon addition - what about other arithmetic operations? Here are the ones you will typically be using, although it helps to be aware of some of the [other operations](https://www.w3schools.com/python/gloss_python_arithmetic_operators.asp) too:

- addition (+),
- subtraction (-),
- multiplication (*),
- division (/),
- exponents (**).

Execute the code block below. Are all of the results exactly what you expect them to be?

In [18]:
x = 10.0
y = 2.0

print("x + y = %s" %(x+y))
print("x - y = %s" %(x-y))
print("x * y = %s" %(x*y))
print("x / y = %s" %(x/y))
print("x ** y = %s" %(x**y))

x + y = 12.0
x - y = 8.0
x * y = 20.0
x / y = 5.0
x ** y = 100.0


### EXERCISE 1

Starting from the defined variables, calculate: (2x - y)/z.

In [96]:
x = '3.2'
y = 2
z = '1.5'

#### YOUR SOLUTION HERE ###

## LISTS

Variables are great and all, but often we'll be working with a ton of variables. Here's where lists come into play: they are the simplest way to store a sequence of information.

In [35]:
x = [1, 2, 3, 4, 5]
y = ['a', 'b', 'c']
print(x, y)

[1, 2, 3, 4, 5] ['a', 'b', 'c']


One can access items in a list by using square brackets ([]) and the 'index' of item they want to index. Remember that Python starts counting from 0, so the first item in a list is indexed by [0], the second is indexed by [1], and so on:

In [36]:
print(y[0])

a


Indexing can also go backwards: -1 corresponds to the last element in the list.

In [48]:
print(x[-1])

5


You can modify lists by indexing, appending, or inserting:

### indexing:

You change the element at a certain index:

In [37]:
y[1] = 'd'

print(y)

['a', 'd', 'c']


### appending:

You append an element to the end of the list:

In [38]:
y.append('e')

print(y)

['a', 'd', 'c', 'e']


### inserting:

You insert an element at a certain index:

In [39]:
y.insert(0, 'f')

print(y)

['f', 'a', 'd', 'c', 'e']


### the + operator:

The "+" operator also acts as an append, when dealing with two lists. You can only add lists to lists, so be wary of the data type that you're using.

In [55]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


### other list operations:

One can check the length of a list using the len() function:

In [40]:
len(y)

5

One can also 'slice' a list - say, we only want the first 3 elements in the list x:

In [46]:
print("Reminder, the original x is: %s"  %(x))
print(x[0:3])

Reminder, the original x is: [1, 2, 3, 4, 5]
[1, 2, 3]


The index "0:3" can be explicitly thought of as index 0 to index 3, not including index 3. In other words, we're slicing out the elements located at an index of 0, and index of 1, and an index of 2.

We don't even have to have the first 0: we can just define the end point of 3:

In [49]:
print(x[:3])

[1, 2, 3]


Similarly, we can only define the start point:

In [51]:
print(x[2:])

[3, 4, 5]


## ARRAYS

Next, let's take a look at **arrays**. I like to think of these as lists on steroids: they're functionally similar, but you can perform many more operations on them. To use arrays, one should first import the numpy module. We installed numpy in tutorial 0 - if you run into an error when running the code block before, let me know or review the 0th tutorial.

In [56]:
import numpy as np

When we write "import numpy as np", we are creating a 'shortcut' - instead of calling "numpy" every single time whenever we want to use a numpy function, we can just write "np". 

One can create an array with np.array() - if you put a list in the middle of those brackets, you create an array. 

In [57]:
x = [1, 2, 3, 4, 5]
y = np.array(x)
print(y)

[1 2 3 4 5]


We can modify arrays in similar ways to lists - by indexing, appending, or inserting:

### indexing:

In [ ]:
a = np.array([1, 2, 3])
a[1] = 4

print(a)

[1 4 3]


### appending:

with np.append(), you put the two arrays you want to append to each other in the brackets.

In [62]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.append(a, b)

print(c)

[1 2 3 4 5 6]


### inserting:

with np.insert, you need: (1) the array, (2) the index where you want to insert something, and (3) the value you want to insert. Explicitly, this is used as: np.insert(array, index, element to insert).

In [64]:
a = np.array([4, 5, 6])
b = np.insert(a, 0, 3)
print(b)

[3 4 5 6]


NOTE! Arrays do not work exactly like lists! Remember that list_A + list_B = [contents of list_A, contents of list_B]. What happens when we try to do that with an array?

In [65]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)

[5 7 9]


Instead of adding all elements of y to the end of x, arrays add together the first element of x and y, the second element of x and y, the third element of x and y, and store those results in a single array. 

This means that other operations will work on arrays. Take a look at the arrays below - are the results what you expect?

In [66]:
c = np.array([10, 20, 30])
d = np.array([2, 2, 2])

print(c + d)
print(c - d)
print(c * d)
print(c / d)

[12 22 32]
[ 8 18 28]
[20 40 60]
[ 5. 10. 15.]


Hopefully this is a good demonstration of why numpy is such a powerful tool: we can perform mathematical operations quickly and seamlessly. We're not limited to addition, subtraction, multiplication, and division either - let's experiment with the following:

- The sum of all elements in an array, using np.sum()
- Averages of all elements in an array, using np.mean() or np.median()
- The minimum and maximum elements in an array, using np.min() or np.max()
- The standard deviation of the elements in an array, using np.std()

In [73]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print('sum of x = %s' %(np.sum(x)))
print('mean of x = %s' %(np.mean(x)))
print('median of x = %s' %(np.median(x)))
print('min. of x = %s' %(np.min(x)))
print('max. of x = %s' %(np.max(x)))
print('std. of x = %s' %(np.std(x)))

sum of x = 55
mean of x = 5.5
median of x = 5.5
min. of x = 1
max. of x = 10
std. of x = 2.8722813232690143


Lastly, it's good to know how to create arrays - two common ways are np.linspace and np.arange. Play around with these, but be paitent. These two operations are very useful, but it takes a couple of practical applications to understand how and why they're used.

### np.linspace(start, end, number of points in between):

In [76]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### np.arange(start, end, step size):

In [77]:
np.arange(1, 11, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**A last note**: what I've shown above does not even begin to scratch the surface of what numpy can do. Chances are you'll run into an operation you don't recognize. If this happens, just google it: numpy is likely the most widely used Python module, is incredibly well documented, and you will most likely be able to find your answer online or in the numpy documentation. Additionally, if there's a mathematical operation that you don't want to code - try looking it up on numpy first, there's a good chance it exists.

### EXERCISE 2

To complete this exercise, make sure that astropy is installed and can be imported into Python. Also make sure that this notebook is in the same folder as "hetmgs_tab1_clean.txt".

In [97]:
# RUN THIS BLOCK OF CODE
from astropy.io import ascii
data = ascii.read('./hetmgs_tab1_clean.txt')
dispersions = np.array(data['sigma'])

It is suspected that nearly every single massive galaxy hosts a central supermassive black hole (SMBH) at its center. One way of obtaining a rough estimate of the SMBH's mass is to measure the galaxy's central velocity dispersion: this is a measurement of how randomly the stars are moving at the center of the galaxy.

In this exercise, you will look at velocity dispersion measurements from [van den Bosch et al. 2016](https://ui.adsabs.harvard.edu/abs/2015ApJS..218...10V/abstract). This paper surveyed ~1200 local galaxies and measured their central velocity dispersions from long-slit spectroscopy, using the Hobby Eberly Telescope at the McDonald Observatory. The dispersions are saved in a variable called "dispersions".

#### PART (A): calculate the median dispersion measured by van den Bosch et al. 2016:

In [99]:
### YOUR ANSWER HERE

#### PART (B): Find $\log_{10}$(median dispersion)

Note! Numpy has two functions that calculate logarithims: np.log, and np.log10. Which one should you use?

In [104]:
### YOUR ANSWER HERE

#### PART (C): Going to a SMBH mass from a velocity dispersion

In order to go to a SMBH mass from a velocity dispersion, one should refer to what are known as scaling relations. Scaling relations are indicative of very weird connections between SMBHs and their host galaxies, but that's a conversation for another time. What you need to know for this exercise: the scaling relation between SMBH mass and central velocity dispersion has been measured many times, but it changes slightly depending on the input assumptions.

[Saglia et al. 2016](https://ui.adsabs.harvard.edu/abs/2016ApJ...818...47S/abstract) contains a fairly up-to-date list of scaling relations, based on the most recent black hole mass measurements. Here are two of the scaling relations that they found:

- $\log_{10}(M_{\rm{BH}}) = 4.772\cdot\log_{10}(\sigma) - 2.476$, if we consider ONLY SMBHs in cored elliptical galaxies.
- $\log_{10}(M_{\rm{BH}}) = 2.192\cdot\log_{10}(\sigma) + 2.526$, if we consider ONLY SMBHs in galaxies with pseudobulges.

In both equations, $\sigma$ is the velocity dispersion, and $M_{\rm{BH}}$ is the SMBH mass. With this information, find:

#### (C, i): The SMBH mass from the mean van den Bosch et al. 2016 dispersion, with both scaling relations.


In [103]:
### YOUR ANSWER HERE

#### (C, ii): The SMBH mass from the smallest van den Bosch et al. 2016 dispersion, with both scaling relations.

In [107]:
### YOUR ANSWER HERE

#### (C, iii): The mean SMBH mass from ALL van den Bosch et al. 2016 dispersions, with both scaling relations.

Here, you should be calculating the SMBH mass that EACH van den Bosch et al. 2016 velocity dispersion corresponds to (using both scaling relations), and then finding the mean of the array of SMBH masses.

In [110]:
### YOUR ANSWER HERE